In [2]:
import pandas as pd

In [3]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')

In [4]:
# show dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [5]:
# set inex
df.set_index('Soil Type', inplace=True)

In [6]:
# show dataframe
df

,Temparature,Humidity,Moisture,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
Soil Type,,,,,,,,
Loamy,29.96,55.46,24.12,Cotton,8,19,16,Urea
Red,36.83,69.28,25.17,Wheat,17,0,28,28-28
Red,26.95,60.64,35.66,Barley,35,4,3,Urea
Red,31.23,44.60,25.08,Maize,17,3,12,DAP
Black,33.78,51.39,47.60,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...
Loamy,35.30,59.61,44.25,Oil seeds,10,14,10,Urea
Black,39.39,71.67,49.34,Barley,35,0,0,10-26-26
Red,35.79,67.64,45.04,Barley,41,0,0,Urea
Black,37.78,73.38,36.03,Tobacco,10,3,30,DAP
Loamy,31.38,48.73,62.27,Millets,11,2,33,28-28

In [7]:
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [8]:
df

           Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
Soil Type
Loamy         24.12     Cotton         8         19           16
Red           25.17      Wheat        17          0           28
Red           35.66     Barley        35          4            3
Red           25.08      Maize        17          3           12
Black         47.60     Cotton         9          9           34
...             ...        ...       ...        ...          ...
Loamy         44.25  Oil seeds        10         14           10
Black         49.34     Barley        35          0            0
Red           45.04     Barley        41          0            0
Black         36.03    Tobacco        10          3           30
Loamy         62.27    Millets        11          2           33

[336 rows x 5 columns]