In [2]:
import pandas as pd

In [3]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [4]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1. isin(): single Filtering

In [5]:
# select 200 or 250 cement content
df_cpcb_dataset['cement'].isin([200,250])

0       False
1       False
2        True
3       False
4       False
        ...
1025    False
1026    False
1027    False
1028    False
1029    False
Name: cement, Length: 1030, dtype: bool

In [6]:
# filter dataframes
df_cpcb_dataset[df_cpcb_dataset['cement'].isin([200,250])].value_counts('cement')

cement
250.0    13
200.0     7
Name: count, dtype: int64

# 2. isin(): Multiple Filtering

In [7]:
# find 14 or 28 age from 200 or 250 cement
filter1 = df_cpcb_dataset['age'].isin([14,28])
filter2 = df_cpcb_dataset['cement'].isin([200,250])

In [8]:
# filter dataframe
filter = filter1 & filter2

In [9]:
df_cpcb_dataset.value_counts(filter)

False    1021
True        9
Name: count, dtype: int64

In [10]:
df_cpcb_dataset[filter1&filter2]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
50,200.0,200.0,0.0,190.0,0.0,1145.0,660.0,28,49.25
248,200.0,0.0,0.0,180.0,0.0,1125.0,845.0,28,12.25
358,250.0,0.0,95.7,187.4,5.5,956.9,861.2,14,24.92
812,250.0,0.0,95.7,191.8,5.3,948.9,857.2,14,24.66
818,250.0,0.0,0.0,182.0,0.0,1100.0,820.0,28,20.87
819,200.0,133.0,0.0,192.0,0.0,965.4,806.2,28,30.44
824,250.0,180.0,95.0,159.0,9.5,860.0,800.0,28,67.87
1004,250.0,0.0,95.7,191.8,5.3,948.9,857.2,28,27.22