In [2]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('rainfall_by_districts_2019.csv')
df_exams.head()

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6

# 1 Selcting two or more columns

In [4]:
# select 2 columns using [[]]
df_exams[['District',"Actual Rainfall in Winter Season (January'18 to and February'18) in mm"]]

,District,Actual Rainfall in Winter Season (January'18 to and February'18) in mm
0,Chennai,3.1
1,Kancheepuram,4.4
2,Tiruvallur,8.1
3,Cuddalore,55.0
4,Villupuram,10.5
5,Vellore,9.8
6,Tiruvannamalai,34.9
7,Salem,15.4
8,Namakkal,26.8
9,Dharmapuri,1.4
10,Krishnagiri,1.3
11,Tiruppur,19.3
12,Coimbatore,12.8
13,Erode,15.1
14,Tiruchirappalli,7.3
15,Karur,15.7
16,Perambalur,18.1
17,Pudukkottai,7.3
18,Thanjavur,21.9
19,Tiruvarur,31.0
20,Nagapattinam,78.8
21,Madurai,6.5
22,Theni,22.8
23,Dindigul,12.6
24,Ramanathapuram,2.2
25,Virudhunagar,28.5
26,Sivaganga,4.1
27,Tirunelveli,25.8
28,Thoothukudi,1.7
29,The Nilgiris,31.4
30,Ariyalur,25.8
31,Kanniyakumari,16.6
32,State Average,18.0

In [5]:
# check out the datatype of the selection
type(df_exams[['District',"Actual Rainfall in Winter Season (January'18 to and February'18) in mm"]])

pandas.core.frame.DataFrame

In [7]:
# select 2 or more columns using [[]]
df_exams[['District',"Total Normal Rainfall (June'17 to May'18) in mm","Total Actual Rainfall (June'17 to May'18) in mm","Actual Rainfall in Winter Season (January'18 to and February'18) in mm"]]

,District,Total Normal Rainfall (June'17 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm
0,Chennai,1324.2,1393.5,3.1
1,Kancheepuram,1227.7,1180.0,4.4
2,Tiruvallur,1139.6,1202.4,8.1
3,Cuddalore,1206.7,1311.0,55.0
4,Villupuram,1011.6,1011.7,10.5
5,Vellore,936.2,1014.0,9.8
6,Tiruvannamalai,1040.0,1234.1,34.9
7,Salem,997.9,1021.2,15.4
8,Namakkal,793.4,845.8,26.8
9,Dharmapuri,902.1,820.8,1.4
10,Krishnagiri,850.7,1019.9,1.3
11,Tiruppur,618.2,834.6,19.3
12,Coimbatore,689.3,1017.2,12.8
13,Erode,702.9,769.4,15.1
14,Tiruchirappalli,818.0,712.8,7.3
15,Karur,655.0,727.3,15.7
16,Perambalur,861.9,962.5,18.1
17,Pudukkottai,887.4,716.3,7.3
18,Thanjavur,1013.1,994.5,21.9
19,Tiruvarur,1173.3,1171.7,31.0
20,Nagapattinam,1393.3,1529.8,78.8
21,Madurai,927.9,875.9,6.5
22,Theni,720.0,976.4,22.8
23,Dindigul,930.7,966.4,12.6
24,Ramanathapuram,807.8,583.4,2.2
25,Virudhunagar,820.1,892.4,28.5
26,Sivaganga,872.8,1074.6,4.1
27,Tirunelveli,845.1,1151.7,25.8
28,Thoothukudi,656.3,614.0,1.7
29,The Nilgiris,1522.7,1488.6,31.4
30,Ariyalur,1071.8,1119.1,25.8
31,Kanniyakumari,1302.5,1317.4,16.6
32,State Average,960.0,1017.2,18.0

In [9]:
# we can't select 2 or more columns with th ","
df_exams.'District',"Actual Rainfall in Winter Season (January'18 to and February'18) in mm"

SyntaxError: invalid syntax (3081328657.py, line 2)