In [1]:
import pandas as pd

In [2]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [3]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1. duplicate()
# 1.1 Example 1

In [4]:
# find duplicate in 2 column/series
df_cpcb_dataset.duplicated('slag')

0       False
1       False
2       False
3       False
4       False
        ...
1025     True
1026     True
1027     True
1028     True
1029     True
Length: 1030, dtype: bool

In [5]:
# show elements in dataframe with duplicate in column 'slag'
df_cpcb_dataset[df_cpcb_dataset.duplicated('slag')]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
5,255.0,0.0,0.0,192.0,0.0,889.8,945.0,90,21.86
7,251.4,0.0,118.3,188.5,6.4,1028.4,757.7,56,36.64
8,296.0,0.0,0.0,192.0,0.0,1085.0,765.0,28,21.65
12,385.0,0.0,0.0,186.0,0.0,966.0,763.0,14,27.92
16,237.5,237.5,0.0,228.0,0.0,932.0,594.0,28,30.08
...,...,...,...,...,...,...,...,...,...
1025,135.0,0.0,166.0,180.0,10.0,961.0,805.0,28,13.29
1026,531.3,0.0,0.0,141.8,28.2,852.1,893.7,3,41.30
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1028,342.0,38.0,0.0,228.0,0.0,932.0,670.0,270,55.06
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61

In [6]:
# duplicate in 2 or more columns
df_cpcb_dataset.duplicated(['cement','slag', 'ash', 'water', 'superplastic'])

0       False
1       False
2       False
3       False
4       False
        ...
1025    False
1026     True
1027    False
1028     True
1029     True
Length: 1030, dtype: bool

In [7]:
duplicated = df_cpcb_dataset.duplicated(['cement','slag', 'ash', 'water', 'superplastic'])

In [8]:
# show all the values duplicated (except for the first - keep='first')
df_cpcb_dataset[duplicated].sort_values(['cement', 'water'])

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
390,102.0,153.0,0.0,192.0,0.0,887.0,942.0,90,25.46
407,102.0,153.0,0.0,192.0,0.0,887.0,942.0,3,4.57
417,102.0,153.0,0.0,192.0,0.0,887.0,942.0,28,17.28
249,108.3,162.4,0.0,203.5,0.0,938.2,849.0,90,29.23
736,108.3,162.4,0.0,203.5,0.0,938.2,849.0,28,20.59
...,...,...,...,...,...,...,...,...,...
661,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,14,59.76
741,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,90,69.66
776,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,180,71.62
935,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,28,67.31
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61

# 1.2 Example 2
Task: Find the etremely high strength and highest cement content laptop of ech company using the sort_values() and duplicated() method(keep "first", "last" and false)

In [9]:
# sort dataframe ascending by cement and strength 
# least strength first and most strength last
df_cpcb_dataset = df_cpcb_dataset.sort_values(['cement','strength'])
df_cpcb_dataset

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
407,102.0,153.0,0.0,192.0,0.0,887.0,942.0,3,4.57
183,102.0,153.0,0.0,192.0,0.0,887.0,942.0,7,7.68
417,102.0,153.0,0.0,192.0,0.0,887.0,942.0,28,17.28
390,102.0,153.0,0.0,192.0,0.0,887.0,942.0,90,25.46
230,108.3,162.4,0.0,203.5,0.0,938.2,849.0,3,2.33
...,...,...,...,...,...,...,...,...,...
935,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,28,67.31
741,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,90,69.66
776,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,180,71.62
313,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,270,74.17
732,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99

In [10]:
# check all value categories in "age" column
df_cpcb_dataset.value_counts('age')

age
28     425
3      134
7      126
56      91
14      62
90      54
100     52
180     26
91      22
365     14
270     13
360      6
120      3
1        2
Name: count, dtype: int64

In [11]:
# duplicate values in "age columns (default -> keep='first')
df_cpcb_dataset.duplicated('age', keep = 'first')

407    False
183    False
417    False
390    False
230     True
       ...
935     True
741     True
776     True
313     True
732     True
Length: 1030, dtype: bool

In [12]:
# show dataframe with duplicated values in "age" column
duplicated_first = df_cpcb_dataset.duplicated('age', keep = 'first')
df_cpcb_dataset[duplicated_first]
# keep='first' (least strength per cement content)
# show dataframe with non duplicated values in "cement" column
df_cpcb_dataset[~duplicated_first][['cement','age']]
# check all value categories
df_cpcb_dataset[~duplicated_first].value_counts('age')

age
1      1
3      1
7      1
14     1
28     1
56     1
90     1
91     1
100    1
120    1
180    1
270    1
360    1
365    1
Name: count, dtype: int64

In [13]:
# show dataframe with duplicated values in "cement" column
duplicated_first = df_cpcb_dataset.duplicated('cement', keep = 'first')
df_cpcb_dataset[duplicated_first]
# keep='first' (least strength per cement content)
# show dataframe with non duplicated values in "cement" column
df_cpcb_dataset[~duplicated_first][['cement','age']]
# check all value categories
df_cpcb_dataset[~duplicated_first].value_counts('cement')

cement
540.0    1
102.0    1
108.3    1
116.0    1
122.6    1
        ..
136.0    1
135.7    1
135.0    1
134.7    1
133.1    1
Name: count, Length: 278, dtype: int64

In [20]:
# keep='last'
duplicated_last = df_cpcb_dataset.duplicated('cement', keep ='last')
#keep=false
duplicated_false = df_cpcb_dataset.duplicated('cement', keep =False)

In [18]:
# keep='last' (highest strength  per  cement content)
# show dataframe with non duplicated values in "cement" column
df_cpcb_dataset[~duplicated_last][['cement','strength']]

     cement  strength
390   102.0     25.46
249   108.3     29.23
81    116.0     31.02
126   122.6     33.19
853   132.0     33.31
..      ...       ...
452   522.0     74.99
256   525.0     67.11
293   528.0     56.83
44    531.3     59.20
732   540.0     79.99

[278 rows x 2 columns]

In [28]:
# keep=false
# show dataframe with non duplicated values in "cement" column
df_cpcb_dataset[~duplicated_false]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
596,133.1,210.2,0.0,195.7,3.1,949.4,795.3,28,28.94
421,134.7,0.0,165.7,180.2,10.0,961.0,804.9,28,13.29
206,136.4,161.6,125.8,171.6,10.4,922.6,764.4,28,29.07
826,139.7,163.9,127.7,236.7,5.8,868.6,655.6,28,35.23
702,139.9,132.6,103.3,200.3,7.4,916.0,753.4,28,36.44
...,...,...,...,...,...,...,...,...,...
506,451.0,0.0,0.0,165.0,11.3,1030.0,745.0,28,78.80
469,485.0,0.0,0.0,146.0,0.0,1120.0,800.0,28,71.99
885,500.1,0.0,0.0,200.0,3.0,1124.4,613.2,28,44.13
320,505.0,0.0,60.0,195.0,0.0,1030.0,630.0,28,64.02
293,528.0,0.0,0.0,185.0,6.9,920.0,720.0,28,56.83

In [31]:
# all elements in cement column are repeated once
df_cpcb_dataset[~duplicated_false].value_counts('cement')

cement
133.1    1
134.7    1
136.4    1
139.7    1
139.9    1
        ..
451.0    1
485.0    1
500.1    1
505.0    1
528.0    1
Name: count, Length: 93, dtype: int64

In [30]:
# all elements in cement column are repeated at least once
df_cpcb_dataset.value_counts('cement')

cement
425.0    20
362.6    20
251.4    15
310.0    14
446.0    14
         ..
146.5     1
145.7     1
405.0     1
528.0     1
436.0     1
Name: count, Length: 278, dtype: int64