In [5]:
import pandas as pd

In [6]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [7]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1 drop_duplicates()

In [8]:
# drop duplicates in 2 or more columns
df_cpcb_dataset.drop_duplicates(['coarseagg'])[['coarseagg','fineagg']].value_counts('coarseagg')

coarseagg
1145.0    1
801.0     1
801.1     1
801.4     1
811.0     1
         ..
827.0     1
825.1     1
825.0     1
824.3     1
824.0     1
Name: count, Length: 284, dtype: int64

In [9]:
# sort dataframe ascending by coarseagg & fineagg
# least first and most last
df_cpcb_dataset = df_cpcb_dataset.sort_values(['coarseagg','fineagg'])

In [10]:
# least: keep=='first'
df_cpcb_dataset.drop_duplicates(['coarseagg'], keep='first')[['coarseagg','fineagg']]

     coarseagg  fineagg
474      801.0    778.0
109      801.1    792.5
903      801.4    778.4
828      811.0    802.0
227      814.0    805.0
..         ...      ...
289     1124.4    613.2
75      1125.0    613.0
192     1130.0    745.0
63      1134.3    605.0
50      1145.0    660.0

[284 rows x 2 columns]

In [11]:
# most expensive : keep='last'
df_cpcb_dataset.drop_duplicates(['coarseagg'], keep='last', inplace=True, ignore_index=True)

In [12]:
# Arguments
# inplace: drop duplicates in place or to return a copy.
#ignore_index=True: the resulting
df_cpcb_dataset[['coarseagg','fineagg']]

     coarseagg  fineagg
0        801.0    802.0
1        801.1    792.5
2        801.4    778.4
3        811.0    802.3
4        814.0    805.0
..         ...      ...
279     1124.4    613.2
280     1125.0    845.0
281     1130.0    745.0
282     1134.3    605.0
283     1145.0    660.0

[284 rows x 2 columns]

# 2 Excercise 1
Task: Find the biggest and smallest age in cement of each strength
using the sort_values() and duplicated() methods (keep "first","last" and False)

In [13]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [14]:
# sort dataframe ascending by age and strength
# smallest first and biggest last (by default)
df_cpcb_dataset.sort_values(['age','strength'])

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
831,385.0,0.0,0.0,186.0,0.0,966.0,763.0,1,6.27
502,500.0,0.0,0.0,200.0,0.0,1125.0,613.0,1,12.64
230,108.3,162.4,0.0,203.5,0.0,938.2,849.0,3,2.33
246,122.6,183.9,0.0,203.5,0.0,958.2,800.1,3,3.32
407,102.0,153.0,0.0,192.0,0.0,887.0,942.0,3,4.57
...,...,...,...,...,...,...,...,...,...
995,380.0,0.0,0.0,228.0,0.0,932.0,670.0,365,52.52
198,266.0,114.0,0.0,228.0,0.0,932.0,670.0,365,52.91
713,190.0,190.0,0.0,228.0,0.0,932.0,670.0,365,53.69
159,304.0,76.0,0.0,228.0,0.0,932.0,670.0,365,55.26
393,342.0,38.0,0.0,228.0,0.0,932.0,670.0,365,56.14

In [15]:
# smallest : keep='first'
df_cpcb_dataset.drop_duplicates(['age'], keep='first')[['age','strength']]

     age  strength
0     28     29.89
1     14     23.51
5     90     21.86
6      7     15.75
7     56     36.64
11     3      6.94
15   100     49.97
27    91     65.20
51   180     39.00
64   365     41.05
149  270     41.15
157  360     44.30
272  120     40.86
502    1     12.64

In [16]:
# biggest : keep='last'
df_cpcb_dataset.drop_duplicates(['age'], keep='last')[['age','strength']]

      age  strength
831     1      6.27
862   120     38.70
919   360     38.11
991    91     75.50
995   365     52.52
996    14     34.24
1003   56     80.20
1008  100     59.30
1012   90     29.39
1017  180     44.21
1026    3     41.30
1027   28     44.28
1028  270     55.06
1029    7     52.61

In [20]:
df_cpcb_dataset.drop_duplicates(['age'], keep=False)[['age','strength']]

Empty DataFrame
Columns: [age, strength]
Index: []