In [22]:
import pandas as pd

In [23]:
# read and show the dataset
df_crop = pd.read_csv("soil_geotech_data.csv")
df_crop

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

# 2.pivot_table()

In [24]:
# make a pivot table and add an aggregete function
df_crop.pivot_table(index="Soil Type", aggfunc="sum")

,Crop Type,Fertilizer Name,Humidity,Moisture,Nitrogen,Phosphorous,Potassium,Temparature
Soil Type,,,,,,,,
Black,CottonOil seedsMaizeBarleyMilletsPulsesPulsesP...,28-2814-35-14Urea10-26-2617-17-1717-17-1720-20...,4211.49,3076.69,1171,1362,296,2185.83
Clayey,Ground NutsMaizeTobaccoSugarcaneMilletsOil see...,20-2020-2028-2814-35-1410-26-2610-26-2617-17-1...,3768.63,2723.95,1090,1317,276,1937.43
Loamy,CottonGround NutsSugarcanePaddySugarcaneOil se...,UreaDAPUrea20-20DAP14-35-1420-2020-2017-17-171...,3310.38,2337.90,862,1071,357,1683.92
Red,WheatBarleyMaizeMaizeTobaccoPulsesTobaccoMaize...,28-28UreaDAP14-35-1420-2010-26-2614-35-1410-26...,4535.46,3126.99,1404,1366,316,2345.77
Sandy,Oil seedsSugarcaneWheatWheatMilletsTobaccoBarl...,14-35-1428-2828-2828-28Urea20-2020-2020-2014-3...,4124.70,3120.11,1234,1214,260,2106.07

In [25]:
# make a pivot table, add am aggregate function and select some columns
df_crop.pivot_table(index="Soil Type", 
                    values=["Moisture", "Temparature"],
                    aggfunc="mean")

            Moisture  Temparature
Soil Type
Black      43.333662    30.786338
Clayey     42.561719    30.272344
Loamy      41.748214    30.070000
Red        41.693200    31.276933
Sandy      44.573000    30.086714

In [27]:
# make a pivot table thet says how much Moisture is required on an average for the specific crop on specified soil type
df_crop.pivot_table(index="Soil Type", columns="Crop Type", values="Moisture", aggfunc="mean")

Crop Type,Barley,Cotton,Ground Nuts,Maize,Millets,Oil seeds,Paddy,Pulses,Sugarcane,Tobacco,Wheat
Soil Type,,,,,,,,,,,
Black,51.4675,39.463333,34.656667,44.602500,43.020000,31.808,43.466000,43.780000,46.216000,46.895000,47.337692
Clayey,39.2480,47.931667,37.586667,48.180000,34.640000,37.906,56.382000,42.912500,33.154286,40.008333,40.522222
Loamy,48.1180,39.826667,37.207500,38.815000,50.198750,33.728,40.920000,36.006000,44.492222,45.600000,38.342500
Red,40.3000,37.601429,41.946667,45.587692,32.714000,45.558,43.873333,43.467143,39.140000,43.778333,39.920000
Sandy,46.4340,42.410000,42.576667,46.394000,49.531111,44.588,30.330000,43.925000,45.666250,45.890000,41.952143